### PR TITLE
Support for IPv6

### PR DESCRIPTION
**Pull request by wallin**
Parse and connect to IPv6 hosts correctly

### CODE REVIEW

**Comment by jhecking** [comment]
Looks good to me. I finally got IPv6 working on my Vagrant dev box today and was able to run some tests for IPv6-only as well as mixed setups.

I noticed only one minor issue with one of the existing specs while testing: The Client#connect spec checks whether the cluster size is >= 1 when using peers protocol as well as the older services protocol. In an IPv6-only setup I found that the older services protocol does not advertize IPv6 addresses. So when the peers protocol is disabled and only one seed node is given for a 2+-node cluster, only that seed node is discovered, but not the remaining nodes. The specs do not catch this. However, we can ignore this, since in a real-world setup, any cluster that supports IPv6 will use the peers protocol for cluster discovery.

**Comment by jhecking** [comment]
@wallin, the PR is still tagged as "WIP" - is there any further work you plan to do on this?

**Comment by wallin** [comment]
@jhecking 

> the PR is still tagged as "WIP" - is there any further work you plan to do on this?

nope. sorry about that. just forgot to change it.

> So when the peers protocol is disabled and only one seed node is given for a 2+-node cluster, only that seed node is discovered, but not the remaining nodes.

Perhaps we could raise an error if IPv6 is used when the peers protocol isn't supported? Happy to take a stab at it in a separate PR

**Comment by jhecking** [comment]
> Perhaps we could raise an error/warning if IPv6 is used when the peers protocol isn't supported? Happy to take a stab at it in a separate PR

How would you know? If one of the seed addresses is IPv6? I think we can just ignore this use case since it only happens during testing. All servers that support IPv6 also support the peers protocol.

**Comment by wallin** [comment]
> How would you know? If one of the seed addresses is IPv6? I think we can just ignore this use case since it only happens during testing. All servers that support IPv6 also support the peers protocol.

Right, that was the idea. But ok let’s ignore this.

**Comment by jhecking** [comment]
@wallin, I've tagged and released [v2.7.0](https://github.com/aerospike/aerospike-client-ruby/releases/tag/v2.7.0). Thanks again for your contributions to this release!

**Pull request merged**
