### PR TITLE
Remove Travis and use GitHub Actions for CI.

### PR DESCRIPTION
**Pull request by ioquatix**

### CODE REVIEW

**Comment by khaf** [comment]
Thanks for the PR. Could you make it so that both are supported for the time being?

**Comment by ioquatix** [comment]
travis.org is shutting down.

**Comment by khaf** [comment]
We still pay for travis.com :)

**Comment by ioquatix** [comment]
Why don't you update that configuration then?

**Comment by khaf** [comment]
Please explain...

**Comment by ioquatix** [comment]
The current Travis configuration appears to be broken, at least on my fork it doesn't work. It looks like maybe it's working for the main repository?

**Comment by khaf** [comment]
The config is working, and I get test results from the Travis.org. We will migrate from Travis in the (near?) future, but for the time being, if you would be so kind as to just adding the Github Action, and leaving the Travis parts as they are, we will gladly take your PR.

**Pull request merged**
