### PR TITLE
Ruby Client v4.2.0

### PR DESCRIPTION
**Pull request by khaf**
[CLIENT-3195] Fix ruby client does not return failed nodes on timeout.

[CLIENT-3195]: https://aerospike.atlassian.net/browse/CLIENT-3195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by justinlee-aerospike — APPROVED** [review]
changes look good

**Comment by opti** [comment]
@khaf any particular reason it was released from the `client_3195_no_nodes_on_timeout_exception` branch instead of merging it to `master` branch?

**Comment by khaf** [comment]
Yes. Our peculiar release process. Why do you ask?

**Comment by opti** [comment]
@khaf for a few reasons:
- makes it harder to maintain a forked version with the latest fixes and our own patches not yet merged to the upstream (which we do)
- makes it harder to propose new pull requests when it's not clear which branch has the latest version

**Pull request closed without merging**
