### PR TITLE
Avoid re-allocating Bignum when checking max value

### PR DESCRIPTION
**Pull request by wallin**
This avoids re-allocating a Bignum every time when a `Value` is created
```
# Allocation trace when running benchmark.rb with 3000 iterations
...
aerospike/value/value.rb:33 T_BIGNUM  12000
...
```

### CODE REVIEW

**Comment by jhecking** [comment]
Good catch! But actually, I believe that code is not just inefficient, but also wrong. [Integer values](https://www.aerospike.com/docs/guide/data-types.html#integer) are stored as 64-bit numerics and therefore should be in the range [ -(2^63), 2^63 - 1 ].

So `INTEGER_MAX` should be `2**63 - 1` and we should also check against `INTEGER_MIN` which should be `-2**63`.

**Comment by jhecking** [comment]
I have temp. removed the check for integer values to demonstrate what would happen when you try to store values outside the range:

````
$ bundle exec pry
[1] pry(main)> require 'aerospike'; include Aerospike;
[2] pry(main)> client = Client.new; key = Key.new('test', 'test', 'int');
[3] pry(main)> max = 2**63 - 1; min = -2**63;
[4] pry(main)> client.put(key, { "max" => max, "min" => min, "max+1" => max + 1, "min-1" => min - 1 });
[5] pry(main)> client.get(key).bins
=> {"max"=>9223372036854775807, "min"=>-9223372036854775808, "max+1"=>-9223372036854775808, "min-1"=>9223372036854775807}
````

And when trying to store such values in a list or map bin, an error gets raised by the Msgpack packer:

````
[6] pry(main)> client.put(key, { "list" => [min - 1, min, max, max + 1] })
RangeError: bignum too big to convert into `long long'
from /Users/jhecking/aerospike/aerospike-client-ruby/lib/aerospike/value/value.rb:200:in `write'
````

**Comment by wallin** [comment]
@jhecking good point! Since it's an Aerospike requirement that integers are in that range, it might make sense to still do the validation and not rely on MsgPack to raise (since that might change in the future)

What do you think about:

```ruby
INTEGER_RANGE = Range.new(-2**63, 2**63 - 1).freeze

# ...

if INTEGER_RANGE.cover?(value)
  # ...
end
```

**Comment by jhecking** [comment]
Yes, that's what I had in mind. Sorry, if the comment about the msgpack packer error was misleading. I was just testing that because integer bins are treated differently from integer values in lists or maps, which use msgpack format internally.

**Comment by wallin** [comment]
@jhecking got it, almost thought so. Let me know if the PR is acceptable now

**Pull request merged**
